server:
  port: 8080
spring:
  application:
    name: monolith-app
  datasource:
    url: jdbc:mysql://localhost:3306/monolith?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
