CREATE TABLE IF NOT EXISTS rate_limit_rule (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  tenant_id VARCHAR(64) NOT NULL,
  env VARCHAR(32) NOT NULL,
  service VARCHAR(128) NOT NULL,
  app VARCHAR(128) NOT NULL,
  qps_threshold INT NOT NULL,
  rt_threshold_ms INT NOT NULL DEFAULT 2000,
  error_ratio_threshold DECIMAL(5,2) NOT NULL DEFAULT 50.00,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
