spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/appdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:appuser}
    password: ${DB_PASSWORD:change-me}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 2
threadpool:
  core: 20
  max: 200
  queue: 1000
app:
  env: ${APP_ENV:prod}
  tenant: ${APP_TENANT:default}
