-- config table (simple)
CREATE TABLE IF NOT EXISTS config (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  env VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  service_name VARCHAR(128) NOT NULL,
  app_name VARCHAR(128) NOT NULL,
  config_key VARCHAR(255) NOT NULL,
  config_value LONGTEXT,
  status VARCHAR(32),
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- rule_store (simplified)
CREATE TABLE IF NOT EXISTS rule_store (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  env VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(128) NOT NULL,
  service_name VARCHAR(128) NOT NULL,
  rule_type VARCHAR(64) NOT NULL,
  rule_key VARCHAR(255) NOT NULL,
  rule_json LONGTEXT,
  active BOOLEAN DEFAULT TRUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- service_registry
CREATE TABLE IF NOT EXISTS service_registry (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  env VARCHAR(32) NOT NULL,
  tenant_id VARCHAR(128),
  service_name VARCHAR(128) NOT NULL,
  instance_id VARCHAR(128) NOT NULL,
  host VARCHAR(128) NOT NULL,
  port INT NOT NULL,
  metadata JSON,
  status VARCHAR(16) DEFAULT 'UP',
  last_heartbeat TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
